#ifndef PINS_HEADER_GUARD
#define PINS_HEADER_GUARD

enum ANALOG_IN
{
	LEFT_TAPE_QRD = 0,
        LEFT_OUTBOARD_QRD = 1,
        RIGHT_OUTBOARD_QRD = 2,
	RIGHT_TAPE_QRD = 3
};

enum MOTORS
{
	LEFT_DRIVE_MOTOR = 0,
	RIGHT_DRIVE_MOTOR = 1,
        GRIPPER_MOTOR = 2,
        LIFTER_MOTOR = 3
};

enum SERVOS
{
	LEFT_RANGEFINDER_SERVO = 0,
	RIGHT_RANGEFINDER_SERVO = 1
};

enum DIGITAL_IN
{
    GRIPPER_RIGHT_SWITCH =0, 
    RIGHT_BUMPER =1,
    LEFT_BUMPER =12,
    LIFTER_SWITCH_TOP =13,
    GRIPPER_LEFT_SWITCH =14,
    LIFTER_SWITCH_BOT =15
};

enum OTHER_CONSTANTS
{
    MAX_MOTOR_SPEED = 1023
};

#endif
