#ifndef PINS_HEADER_GUARD
#define PINS_HEADER_GUARD

enum ANALOG_IN
{
	LEFT_TAPE_QRD = 0,
	RIGHT_TAPE_QRD = 1, 
	LEFT_OUTBOARD_QRD = 2, 
	RIGHT_OUTBOARD_QRD = 3,
	LEFT_RANGEFINDER = 4,
	RIGHT_RANGEFINDER = 5
};

enum MOTORS
{
	LEFT_DRIVE_MOTOR = 0,
	RIGHT_DRIVE_MOTOR = 1,
    GRIPPER_MOTOR = 2,
    LIFTER_MOTOR = 3
};

enum SERVOS
{
	LEFT_RANGEFINDER_SERVO = 0,
	RIGHT_RANGEFINDER_SERVO = 1
};

enum DIGITAL_IN
{
    LEFT_BUMPER = 0,
    RIGHT_BUMPER = 1,
    GRIPPER_LEFT_SWITCH = 2,
    GRIPPER_RIGHT_SWITCH = 3,
    LIFTER_SWITCH_BOT = 4,
    LIFTER_SWITCH_MID = 5,
    LIFTER_SWITCH_TOP = 6
};

enum OTHER_CONSTANTS
{
    MAX_MOTOR_SPEED = 1023
};

#endif
